### ISSUE TITLE
Bubble chart works only for Politecnico di torino

### ISSUE THREAD

**Issue by nicorusti** [giuseppefutia/vis-public-contracts#15]
By searching other PA, the bubble chart doesn't show up

**Comment by alemela** [comment]
We've to understand if the problem is in the query SPARQL call or in the visualization template. Could you please provide one or two example in which you'd expect the bubble chart?

**Comment by nicorusti** [comment]
I think there should be a bubble chart for every pa. 
Politecnico di milano, for example, has no bubble chart 
80057930150

**Comment by alemela** [comment]
Thanks I noticed that is the uduvudu http://public-contracts.nexacenter.org/id/hasContract matcher that works only for Polito, but haven't understood why, yet.

**Comment by nicorusti** [comment]
That is a virtual property assigned in the CONSTRUCT sparql Query. There must be something wrong there

**Comment by alemela** [comment]
I read some SPARQL answers and all seem to be complete. I haven't seen any difference between polito's one and others but I want to check more.

**Comment by alemela** [comment]
Find out! https://github.com/giuseppefutia/vis-public-contracts/commit/0ae3cc5dde91ea638d0aea3f20d63deaeb865c67 Now it works!

**Comment by giuseppefutia** [comment]
#edaidaidai

**Comment by nicorusti** [comment]
If possible, i would add to the bubble chart (when mouse is passed on a bubble), some additional information about the contract (i.e. The name of the awarded tender), then i would make the bubble clickable so that you can go to see the rdf

**Comment by giuseppefutia** [comment]
@nicorusti ok! I think you could open a new issue for that! Thanks!
