### ISSUE TITLE
It's quite confusing which vis refers to income and which to outcome

### ISSUE THREAD

**Issue by alemela** [giuseppefutia/vis-public-contracts#8]
Actually the layout is divided by type of visualization. This tends to tangle informations to the point of not understanding well which is an income contracts and which is an outcome one.

**Comment by giuseppefutia** [comment]
I agree with you, Alessio. Probably we should divide the visualizations and distinguish the 2 cases with clearer labels. What about these two titles:
- Bandi di gara e contratti pubblicati dal soggetto
- Bandi di gare e contratti assegnati al soggetto

**Comment by alemela** [comment]
Done by @giuseppefutia
